# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
---
- name: Set up for OPI LAB environment
  hosts: all
  become: yes
  tasks:
    - import_tasks: debian.yml
      when: ansible_os_family == 'Debian'

    - import_tasks: redhat.yml
      when: ansible_os_family == 'RedHat'

    #- import_tasks: suse.yml
    #  when: ansible_os_family == 'Suse'

    - name: Testing
      shell: uname -a
