# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
---
- name: Set up for OPI LAB environment
  hosts: all
  become: yes
  tasks:
    - include: debian.yml
      when: ansible_os_family == 'Debian'

    - include: redhat.yml
      when: ansible_os_family == 'RedHat'

    - include: suse.yml
      when: ansible_os_family == 'Suse'

    - name: Testing
      shell: uname -a
